### ISSUE TITLE
Restore support for no-LPM runs

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#108]
There is a request to reestablish support for single-partition runs that do not rely on the LPM and instead rely only on iCI and PI controllers. I suggest introducing a local run key switch for disabling the features that require an LPM and for enabling the required configuring of the iCI/PI for "standalone" runs.

**Comment by sethcooper** [comment]
We should check to make sure that the same configuration can have all the required connections for this and still function in both multi- and single-partition modes.
Also, this will require 1 new run key for each type of run and partition (should also include masking the other partitions or else we will have multiple iCIs trying to generate triggers and so on). An alternative implementation which would not require extra run keys would be to activate this mode automatically based on the unmasked resources (plus consistency check) and have separate iCI/PI configurations available in each run key for multi- and single-partition modes.

**Comment by jhakala** [comment]
This appears to work out of the box (based on 904).
