### ISSUE TITLE
Move local run keys out of RSDB userxml and into "grandmaster" snippet

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#110]
The list of local run keys is currently defined in the levelOne's userXML, which is only editable/viewable in the RSDB viewer in the RSManager. However, we could move this info out of the userXML into a new kind of "grandmaster" snippet. Ultimately, the userXML could be boiled down to one line:
`<userXML CfgCvsBasePath="~hcalsw/cfgcvs" Grandmaster="grandmasters/example.xml" />`

**Comment by sethcooper** [comment]
Anything in the UserXML could alternatively be specified as a Property of the Level1 FM. I guess the only real advantage of that would be not having to parse the UserXML.
