### ISSUE TITLE
Fix global+minidaq HF laser mastersnippet names

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#112]
The minidaq and global laser mastersnippets have counterintuitive names. We should fix this or follow up with an HCALDAQ on call to get this straightened out.

**Comment by jhakala** [comment]
Martin did this -- Martin, would you please close the related JIRA ticket?

**Comment by kakwok** [comment]
I did not know there's a JIRA ticket for this and I cannot find it under the CMSHCAL JIRA.
Can you post link here?
