### ISSUE TITLE
Logsession ID=0 if run is not properly stopped

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#116]
Currently,we do RunInfoPublish during stoppingAction/haltAction/coldReset/ResetAction.
If a local run was destroyed without stopping (mostly due to errors), then we will publish a sessionID=0 which is the default value.
We could consider adding extra RunInfoPublish places for local runs (e.g. RunningAction)

**Comment by kakwok** [comment]
Not publishing in time does not explain why the RunNumber was correctly obtained and sent out for these abruptly destroyed runs.
- Make sure run number is handled the same way as the SID in our side
- Should follow up with Hannes if we confirmed that.

**Comment by jhakala** [comment]
Any updates on this issue?

**Comment by kakwok** [comment]
Should be fixed by 1fed6cc64d02c3d9690419527c15a90b5f4e23e1
