### ISSUE TITLE
Fix error message from NotificationHandler

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#118]
In StatenotificationHandler, processNotice()
When the supervisor sends an "ERROR" or "FAILED" notification to FM, the LV1 FM now reports the wrong LV2 FM name that is in ERROR.
The LV1 should loop through it's LV2s, see which are in errors and try to rely the error messages from the failed Supervisor(SuperErr)

**Comment by sethcooper** [comment]
The Level-1 will now get the error notification from the Level-2, with the "reason" of the Level-2 notification containing the supervisor error.  In general anything can be put into the "reason" field, not just supervisor errors (although that's the current use case) so we may want to rename the GUI parameter.
A PR is forthcoming for this (after a bit of cleaning).
