### ISSUE TITLE
Supervisor error-handling improvement

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#127]
There is a spot for the "reason" for a state change notification in the rcms state listener.
This could be used to send the "supervisorError" messages to the FM in the notification itself instead of querying them via SOAP/infospace as we do now.
In this case, the error could be extracted by calling getReason() on the notification event.
This should be tested.
Would fix #118 as well

**Comment by kakwok** [comment]
FM side (LV2 query supervisor infospace->LV1 notification) is done.
The improvement to be made is on xdaq side (supervisor setting the reason when reporting to LV2)

**Comment by kakwok** [comment]
Related to https://gitlab.cern.ch/cmshcos/hcal/issues/42.
We should update this line when that issue has been implemented
https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALStateNotificationHandler.java#L158

**Comment by kakwok** [comment]
hcos issue is done, but we decided to format the error message with more information than just a string from supervisor, so notification reason is not sufficient for the purpose.
See #374 and #391
