### ISSUE TITLE
Set reasons for errors

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#128]
In the goToError functions, we should probably be making a new Input and doing setReason on it (for firePriorityEvent ERROR).
In this case, I think the "Reported reason" that the cdaq shifter often posts would actually be filled.
Usually it's empty, e.g.,
"[2016-06-10 10:18:45 CEST Run 274885] [http://cmsrc-hcal.cms:16000/urn:rcms-fm:fullpath=/hcalpro/USC/test/GLOBAL_HCAL_allCrates_noLaser_NewFM,group=HCAL_HBHEc,owner=hcalpro] is in Error Reported reason:
"

**Comment by jhakala** [comment]
Should this be closed per PR #155?

**Comment by sethcooper** [comment]
Yes! I wasn't assigned to this one, so I missed it.
