### ISSUE TITLE
Remove useless error message during RunInfoPublish for LV1

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#130]
ERROR [HCAL HCAL_LEVEL_1] Error! publishRunInfoSummaryfromXDAQ() requested but no hcalRunInfoServer application found - please check!

The offending line is:
https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALEventHandler.java#L2027

where the error is suppressed based on the FM Role. This works for HCAL, but not HF, which has the role assigned as "HF".

We should also give a better name for the HF level-1 FM because that is confusing.

**Comment by jhakala** [comment]
Done in commit 8ca1f86 by not calling publishRunInfoSummaryfromXDAQ() in the level1.
