### ISSUE TITLE
Spontaneous errors during Halted in global

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#131]
Occasionally we randomly go to error while sitting in halted while in global. At first glance, it looks like this is an internal bug in the l0, but we should investigate.

**Comment by kakwok** [comment]
For the two times I have seen with the timeline, it's always 4mins:
![image](https://cloud.githubusercontent.com/assets/12798013/17103431/89e31678-527e-11e6-999d-e391dbece746.png)

**Comment by jhakala** [comment]
We tracked the error down to a bug in how we stop the timeout thread. This probably should be fixed by modifying the job scheduler to schedule the halting sequence like other transitions (besides initialize).

**Comment by sethcooper** [comment]
Scheduling won't fix this particular problem, because it happens in initializing, but it's a good idea anyway.

**Comment by kakwok** [comment]
Shortening the timeout thread does not reveal this problem in H2. Need further investigation.

**Comment by sethcooper** [comment]
Fixed with #157
