### ISSUE TITLE
Parameters gone in gui

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#134]
There has been reports from DOC that the FM parameters displayed will disappear. I experienced that today on starting and stayed there on running. Refreshing the page solved the problem.

![image](https://cloud.githubusercontent.com/assets/12798013/17270055/6ef8060a-5659-11e6-848d-d3c5eb39a615.png)

This is a browser dependent problem and John identified the browser is running JS before it loads the html.

**Comment by jhakala** [comment]
I think I've fixed this in commit  8c39e1b.
