### ISSUE TITLE
Get NumberOfEvents earlier than configure

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#152]
We should show user as early as possible what is the default NumberOfEvents set in the MasterSnippet.
We should at least parse the FMSettings tag during initAction. 
A more radical proposal is to parse the mastersnippet during init instead of configure, which should in principle just work as the results of parsing is stored in the FM's parameterSet.
We simply have to get the values from the parameterSet before sending them to LV2s

**Comment by jhakala** [comment]
Similar to #202, if we want the number of events to appear instantaneously upon selecting a run key, the number of events for each run key should be propagated into the AVAILABLE_RUN_CONFIGS parameter so that they can be associated in the GUI with the local run keys.

**Comment by jhakala** [comment]
Is this done?

**Comment by jhakala** [comment]
Hopefully resolved by #313.
