### ISSUE TITLE
Clean up Trigger key handling

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#154]
Right now we dynamically write part of the CfgScript to handle Trigger Keys, and we also did at least in the past for the ZS settings.
We should simply remove this.
The TriggerKey is already sent to the supervisor via infospace, and the code is in place on the xdaq side to read it from the infospace if it's not specified elsewhere the CfgScript (and it is not).

I guess the main reason for writing in the snippets was to keep track of the configuration information for future reference.  Instead of that, this should be done by looking at Cfg parameters exported to a DB, ideally using CfgRecord and the conditions DB. But probably the easiest way to get started on this is to export a few important Cfg parameters (like in this case, the trigger key name, in addition to the "tpgtagname" which is already exported) into the xdaq runinfo and publish it into the run info DB.  In this case, the trigger key is even already listed in the RunSummary WBM page.

**Comment by jhakala** [comment]
Apparently we used to specify the trigger key in the cfgScript until sometime between March 20th and March 23rd. For example, using the RunInfoDiffer on runs 312225 and 312538, I see:
```
- HTR { HcalTriggerKey = "Physics2018testv3" } uHTR { HcalTriggerKey = "Physics2018testv3" }
+ HTR { HcalTriggerKey = "" } uHTR { HcalTriggerKey = "" }
```
The fact that we have something presumably incorrect getting written into the cfgScript as well as into the RunInfo is bad. We should remove whatever code is adding this incorrect info to the cfgScript.
