### ISSUE TITLE
Run Control FM mask GUI bug

### ISSUE THREAD

**Issue by Spudmeister** [HCALRunControl/levelOneHCALFM#167]
When clicking the mask - FM button in the gui, the visible list is appended to, so if you unclick, the gui does not clear the relevant FM and if you then reclick to mask it, you will end up with the FM being listed twice.

**Comment by jhakala** [comment]
Which version are you using? Perhaps it's out of date. This was fixed a few weeks ago. See if you can reproduce it on an up-to-date teststand: http://cmshcaltb02:16000/rcms/

**Comment by kakwok** [comment]
This works at H2, so 904 needs an FM update if this feature is desired.
