### ISSUE TITLE
Remove code for FU/BU/EVM/FEDStreamers...

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#172]
We don't have any those in our current configurations (and don't have any plans to include them), so the code can be removed.
Example block of code to be removed:
https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALlevelTwoEventHandler.java#L1169-L1332

**Comment by kakwok** [comment]
done in #186
