### ISSUE TITLE
Fix CONFIGURED_WITH_FED_ENABLE_MASK parameter in global

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#176]
It looks like some sort of trigger key or other db tag is being filled into into a parameter reserved for a certain FED_ENABLE_MASK when it shouldn't be:
<img width="754" alt="weird_configuredwithfedenablemask" src="https://cloud.githubusercontent.com/assets/8178838/18233264/5b17afc8-72e2-11e6-9e39-f995043060f3.png">
We should fix this

**Comment by kakwok** [comment]
Fixed in 8cccdff
