### ISSUE TITLE
Publish full cfgscript to runinfo

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#181]
We should publish the full CfgScript (as parsed by the supervisor) to run info.
Could do this the current way, by having the supervisor send this to the RunInfoServer.

**Comment by jhakala** [comment]
I don't think anything needs to be done on the FM side for this, so I suggest closing the issue and opening a ticket in the HCOS JIRA instead.

**Comment by sethcooper** [comment]
We'll need a new RunInfo parameter in the hcalFM code, right?

**Comment by jhakala** [comment]
Nope, the RunInfoServerReader gets the names of the parameters (as well as their values) from the RunInfoServer. You can see here: https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALEventHandler.java#L1344
This is why it was easy for us to add things like e.g. the uTCA boards' firmware versions into the RunInfo without any FM updates on our side.

**Comment by sethcooper** [comment]
This is published as CFGDOC_TXT by the supervisor starting in hcos 13.4.0
