### ISSUE TITLE
Unknown halt notification during halted

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#184]
Seth noticed that we got a Halt input while HCAL and HF were already in halted for a while. There are not much hint in the log where this notification came from. We should put better log messages for task completion/monitoring.

`2016-10-09 07:40:19 and 0 ms : cms.hcalpro.rcms.statemachine.StateMachineEngine
    ERROR Transition for input Halt and State Halted not defined
2016-10-09 07:40:19 and 0 ms : cms.hcalpro.rcms.fm.fw.EventProcessor
    ERROR State Machine error for Input Halt
2016-10-09 07:40:19 and 3 ms : cms.hcalpro.rcms.statemachine.StateMachineEngine
    ERROR Transition for input Halt and State Halted not defined
2016-10-09 07:40:19 and 3 ms : cms.hcalpro.rcms.fm.fw.EventProcessor
    ERROR State Machine error for Input Halt`

**Comment by jhakala** [comment]
Has this been followed-up? I haven't seen this in the logs at all so I think this deserves a "not reproducible".
