### ISSUE TITLE
Increase allowed time for configuring for Cold-init

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#187]
Cold-init takes longer time. Supervisor may update its state to cold-init after FM tells it to init.
We should handle the notification from supervisor to extend the allowed transition time in that case.
This will be useful when we commission the upgrades

**Comment by sethcooper** [comment]
I think the consensus here was to:
1) Add a new FM state for Cold-Init (ColdConfiguring?)
2) In this state, make an action message saying that it could take a while due to firmware reloading, etc.

**Comment by kakwok** [comment]
Action message will show configuring progress (overall percentages), done in #198
