### ISSUE TITLE
Correct double-writing of MASKED_RESOURCES

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#189]
The MASKED_RESOURCES parameter seems to be getting as many as three copies of masked apps: e.g.
```["HCAL_Laser","hcalLaserController_0","hcal::GapOperationsManager_0","hcal::uMNioManager_0","DummyTriggerAdapter_1","hcalEventBuilder_1","hcalTrivialFU_1","hcalEventBuilder_5","hcalTrivialFU_5","FanoutTTCciTA_0","Executive_18","JobControl","tcds::ici::ICIController_3","tcds::pi::PIController_3","Executive_40","hcalCrate_9","hcal::DTCManager_9","hcal::uHTRManager_9","hcal::GapOperationsManager_0","hcal::uMNioManager_0","hcalLaserController_0","DummyTriggerAdapter_3","hcal::DTCReadout_9","hcalEventBuilder_3","hcalTrivialFU_3","Executive_20","hcalPartitionViewer_3","hcalSupervisor_3","Executive_19","JobControl","hcalRunInfoServer_3","DummyTriggerAdapter_3","hcalEventBuilder_3","hcalTrivialFU_3","hcalEventBuilder_4","DummyTriggerAdapter_4","hcalTrivialFU_4","DummyTriggerAdapter_0","hcalEventBuilder_0","hcalTrivialFU_0","hcalLaserController_0","hcal::GapOperationsManager_0","hcal::uMNioManager_0"]```
This should be fixed.

**Comment by kakwok** [comment]
#221 Does not fix all duplicate writing. To be investigated further

**Comment by jhakala** [comment]
I think  #310 fixes the remaining double-writes.
