### ISSUE TITLE
Stale FM when destroyAction timed-out

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#190]
We had a case today when a PC went down during configuring and leading to a timeout when JC later tried to destroy the XDAQ.
`2016-11-03 15:45:36 and 715 ms : cms.hcalpro.rcms.fm.resource.qualifiedresource.JobControl
     ERROR JobControl::killJid() XDAQTimeoutException (check xdaqctl) for: http://hcalvme05.cms:9999: elapsed time=20001 ms  msg.timeout=20000 ms.Exception thrown: Elapsed time=20001 ms Timeout=20000 ms on : http://hcalvme05.cms:9999
`
The LV2 failed to destroy due to timeout and threw an exception. LV1 FM simply caught the exception and completed it's own destroy. Interestingly, the remaining LV2 FMs in the loop to destroy are left un-destroyed with their XDAQ. 
Without their LV1, these LV2 cannot be destroyed from GUI nor monitoring tool. Re-init same configuration then destroy fixed the problem.

**Comment by jhakala** [comment]
Is the goal here to simply try harder to destroy as much as possible after destroy has failed? If so, I doubt this should be labelled "medium" priority. Re-initializing after a failed destroy is necessary, so the fix is already automatic, no?

**Comment by kakwok** [comment]
The goal is to 1)not leave a stale FM and 2)don't fail silently on destroy if there is exception.

**Comment by jhakala** [comment]
Not leaving a stale FM is nice, but in this case, it's a foregone conclusion that there will be at least one stale FM, right? So the aim is to destroy all the other FMs besides the one that really failed to destroy? 

With regards to failing on destroy, there is no way the L1 should be able to stay alive for very long after something goes wrong on destroy, so any complaint it makes will go away almost instantly, besides the complaints in the logs. Adding more red to the logs may or may not help, but there is little point in trying to put the FM into a complainy state for the few seconds it has before it gets destroyed.

**Comment by sethcooper** [comment]
I don't know about the stale FM, but it's good to have the GUI dialog box telling the user that something went wrong with the destroy.  This is the upshot of the exception handling.  In the cases where this is not fixed by a simple re-init, or if the user moves to a different run key with different masking, and the issue returns, this will make it much easier for HCAL DAQ experts to debug. The cDAQ shifter should also get some notification about this in global for the same reason.
