### ISSUE TITLE
Support single- and multi-partition modes (server side)

### ISSUE THREAD

**Issue by DryRun** [HCALRunControl/levelOneHCALFM#193]
Plans to support running single- or multi-partition modes. The idea is that multiple single partitions can be running simultaneously with one multi-partition. As there is only one LPM, the FM needs to know which mode it is in, and configure accordingly. 

Notes from the discussion on 11/11:

Master snippet changes:
-  Change TCDSControl to ICIControlSingle
-  Add ICIControlMultiple
-  Also PIControl needs single and multiple versions.

Controlling whether the FM is in single vs multiple partition mode:
-  Martin has some logic from the alarmer check to count the partitions. Use this to count partitions for this case. 
-  If more than one, configuration is multiple partition.
-  Cases:
-  * Multiple partitions and LPM present: use multipartition configuration.
-  * Multiple partitions and no LPM: inconsistent, go to error
-  * Single partition and LPM present: use multipartition. Occupies the LPM needlessly, but not inconsistent. 
-  * Single partition and LPM: use single partition configuration.

**Comment by sethcooper** [comment]
See also #121 #108

**Comment by jhakala** [comment]
Do we foresee this being a non-trivial use case in the near future? The overhead of automating this logic seems to be overkill when it only takes a few minutes to change snippets/run keys accordingly to get a no-LPM singlepartition run -- unless we think that this use case will be in high demand in the near future and poses an advantage over making 5 or 10 new run keys for these special use cases.

**Comment by sethcooper** [comment]
As repeatedly discussed, I expect this to be heavily used during YETS. People are going to want to take single-partition runs all the time and in parallel, and this will help us keep the number of run keys down to a manageable level. The "snippet configuration" and the user-defined masking, including local or multipartition choices, should be separated.

**Comment by jhakala** [comment]
In order to achieve the decided-upon goal (we want five/six identical configurations [one for each partition] which can be used for arbitrary single or multipartition runs, without duplication of mastersnippets), we would like to have #110 implemented so that the addition of a run key will not require changing all the identical configurations' userXML.

**Comment by jhakala** [comment]
I think Martin has implemented this. Please close if so.
