### ISSUE TITLE
Allow unmasking of run-key masked FM in GUI

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#202]
1) Fill maskedFM from the runkey to the parameter AVAILABLE_RUN_CONFIGS in the format: 
 name:snippet:maskedFM:maskedapps
2) GUI pre-fills the check-box(es) of maskedFM
3) Pick the correct FM (according to GUI and runkey) to mask during masking.
Right now, I think we fill what's masked in the runkey no matter what the GUI says.

**Comment by jhakala** [comment]
done in 430d9d1
