### ISSUE TITLE
Fix logic for pollingReadout setting in localDAQFM scheme

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#208]
Right now, a crucial ingredient for successful EvmTrig operation is that we find a DTCReadout in the same executive as the EvmTrig DummyTriggerAdapter, and give it a special setting: pollingReadout=True. In the upcoming configuration scheme with a new "networkTriggerAdapter" developed by Seth, the TA will not live in an executive with a DTCReadout, but will require one of them to be in pollingReadout mode. We will need to figure out how to handle this appropriately.

**Comment by sethcooper** [comment]
The DummyTA simply chooses the first DTCReadout it finds and sets it to be in PollingMode (along with telling it where to send its trigger blocks).  (Later we can extend this to other ReadoutApplications.)  So new no logic on the FM side should be needed.

**Comment by jhakala** [comment]
We should make sure, however, of whether or not the TA-sibling DTC seeking mechanism that we currently use doesn't bork things up -- and if it does we could either remove it or turn it on/off using a "legacy mode" switch.

**Comment by sethcooper** [comment]
I would be a bit surprised if that was the case, as no TA will share its exec with any readout (by construction), but of course if we run into problems we can rethink it. For now we can leave it in place.

**Comment by jhakala** [comment]
Yes, after looking at it, I think the existing logic will simply do nothing if there's no dummyTA. So, basta.
