### ISSUE TITLE
Configure EVMTrig FM last

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#215]
The local DAQ FM needs to be configured last in order to properly handle the case where we have a multiFED amc13 reading out in local in a separate executive from the eventbuilder.

**Comment by kakwok** [comment]
EvmTrig FM and LPM FM configure last as is now, should review if LPM FM needs to configure together with EvmTrig FM

**Comment by kakwok** [comment]
LPM FM was configured together with EvmTrig FM because TTCci FM is configured by EvmTrig supervisor. Instead tying LPM FM with EvmTrig FM, TTCci FM should be distinguished from LPM FM.
