### ISSUE TITLE
Exception on destroy causing dialog box

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#225]
Return of the exception dialog box on destroy.
Observed at 904 with currently-deployed FM (c7de664/handleTCDS).
Possibly due to Exiting or issuing the Halt to TCDS apps.
![image](https://cloud.githubusercontent.com/assets/4696879/22555394/dcef75f6-e963-11e6-919c-114a178253bd.png)

**Comment by jhakala** [comment]
We should test whether or not this happens after PR #231 is merged. 

I think this dialog box is unavoidable for a spectator on a run -- but if this happens to the taker of the run, then that's a bug.

**Comment by jhakala** [comment]
Should be resolved in PR #235.
