### ISSUE TITLE
color of progress bar

### ISSUE THREAD

**Issue by elaird** [HCALRunControl/levelOneHCALFM#227]
It would facilitate understanding the state at a glance if both
a) the color of the progress bar during configuring matches the color of the word "Configuring";
b) the color of the progress bar while acquiring events matches the color of the word "Running".

I would have no strong preference when RunningDegraded, as it occurs less frequently and anyway typically requires further attention from the user.

**Comment by jhakala** [comment]
Done in 831e0df.
