### ISSUE TITLE
Do not fill maskedapps in MaskedResources on GUI

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#244]
Maskedapps can get pretty long when we get a global config from local by masking.
We do not need a lot of maskedapps in P5 now, so it's not urgent at the moment, but will be an important feature.
![image](https://cloud.githubusercontent.com/assets/12798013/23177777/61ff46be-f868-11e6-94ec-955229d3240f.png)

**Comment by jhakala** [comment]
done in 5b044a4
