### ISSUE TITLE
Display multi/single partition selection to user and spectator

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#257]
It is possible to display the single/multipartition mode that has been selected to the user after they have selected it?  And this would be useful for spectators as well.

**Comment by jhakala** [comment]
Yes, one would just have to parse the single/multipartition parameter (SINGLEPARTITION_MODE) and have the javascript turn on the visibility of the corresponding panel (which will automatically reflect the selection that's been made). I guess you'd also want to disable that panel from being modified -- i.e. a read-only mode.

How would we want this to work? Should there be a button that says "display masking panel" or something? I don't think it's helpful to force it to be visible all the time.

**Comment by kakwok** [comment]
I like it better to have it visible all the time.  Since we have a big blue button in the GUI, having it always there to remind people (Us for debugging or users to check what they have just done) is very useful.

**Comment by sethcooper** [comment]
I agree. I like babying the users... :-)

**Comment by jhakala** [comment]
On second thought, this actually won't work automatically if we simply show the panel. Right now, if we simply showed the panel, it would "prefill" the masks that are specified in the local run key -- it would _not_ reflect the masks correctly if the user modified them from their default run key settings. So probably the most efficient way of doing this would be to try parsing the MASK_SUMMARY to get that info to make sure the checkboxes reflect that. It seems to be kind of a lot of overhead to support this fairly redundant feature.

**Comment by kakwok** [comment]
done in ece8027
