### ISSUE TITLE
Bug in error handling during initialize

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#26]
Right now, if an error occurs during initialize, it can cause an error state to occur. However, the function managers (including level-1) appear to go to Halted anyway, even though the transition is not marked as complete. Eventually, the transition to halted times out, since it's not marked as complete, and the state does go to error. But it should go to error right away, and not to halted first.Bug in error handling during initialize

**Comment by sethcooper** [comment]
I am not sure about this. I've been unable to reproduce at H2 or P5.
Is this reproducible at 904?

**Comment by jhakala** [comment]
I don't think this is an issue any more due to the SID/LogSessionConnector fix.
