### ISSUE TITLE
Display partitions included/excluded in a run

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#272]
With init/configure masking used so often now, we should present clear information of what is included/excluded in the run.
For local run, this is less of a problem because Mask Summary contains the information, although not ideal for someone to read what's in and what's out in 1 sec.
For global run, this information is hidden deep in "EMPTY_FMS" value. 
I think we should have a unified display for both init-masked and configure-masked FMs.

**Comment by kakwok** [comment]
related to #68

**Comment by kakwok** [comment]
A simpler implementation would be to display what FEDs are included/excluded based on `FED_ENABLE_MASK` received on the GUI, similar to what the LV0 has in the FED&TTS tab.

**Comment by jhakala** [comment]
Done in #392.
