### ISSUE TITLE
Negative configuration progress

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#273]
EmptyFM calculation is probably causing negative configuration progress.
https://github.com/HCALRunControl/levelOneHCALFM/blob/master/src/rcms/fm/app/level1/HCALlevelOneEventHandler.java#L902

**Comment by jhakala** [comment]
I think that the EmptyFM calculation is causing the non-100% configuration progress despite reaching Configured. On the other hand, I think the negative values of the configuration progress are due to negative numbers being received from the Supervisor.

**Comment by kakwok** [comment]
EmptyFM calculation was wrong only for first configuration with non-zero emptyFM and you are right that it has nothing to do with negative progress. It probably confused some shifters seeing the fish reporting incorrect configuration progress.
Negative progress, on the other hand, in most cases is from `-1` default value of the `PROGRESS` parameter in LV2 FMs. SupervisorWatchThread updates `PROGRESS` every 5s, but ProgressThread updates every second, so some times we started with negative progress, but after 5s into configuring, it should be cured.
I am not sure if supervisor would indeed report negative progress, but I doubt it.

**Comment by kakwok** [comment]
Fixed in b33ffff
