### ISSUE TITLE
Fix Error->Reset

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#276]
I think there may be a problem with the Error -> Reset behavior. For example, I set a "nsamples" that was too large (100) in the uHTR context, and this, as expected, caused an error on Configure. I changed the value and hit Reset (since this works to pick up snippet changes), but instead of going back to Halted, the level1 hung in Resetting. Please investigate.

**Comment by kakwok** [comment]
Was there just one LV2 that did not go to halted? or was none going to halted?
In resetting, LV2 should do destroy and initXDAQ in one go, so I would suspect one of the LV2 went wrong during the process. Could you provide more information?

**Comment by jhakala** [comment]
It looks that both level2s are in Halted but the level1 is stuck in Resetting.
![screenshot-7](https://cloud.githubusercontent.com/assets/8178838/25014301/c4bd6b7c-203c-11e7-870f-e5ab29cf452a.png)

**Comment by kakwok** [comment]
This is due to LV1 trying to resume the configuring task sequence. We could clear the on-going taskSequence if we go to error at some point in the sequence.

**Comment by kakwok** [comment]
Fixed in 2f75232.
