### ISSUE TITLE
Pick LaserFM as EvmTrig FM if included

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#279]
Following the discussion in [1], Laser FM, which contains the calibration units that sends data to HBHEc, should be configured after HBHEc if included. One way to ensure this would be to pick LaserFM as EvmTrig FM whenever it is included.   

[1] https://gitlab.cern.ch/cmshcos/hcal/issues/15

**Comment by jhakala** [comment]
It might be good to add something configurable, like e.g. adding an "EVMtrig preference" parameter (perhaps some sort of JSON list) into the FMSettings. Compared to hardcoding in some FM name matching, this could in theory provide us some additional flexibility to deal with cross-partition snafus in the future, and would at least leave some trace in HcalCfg about what the FM is doing (as opposed to burying hardcoded logic in the FM code). So I'd suggest changing the issue name to "Support configurable EVMtrig FM preferences".

**Comment by kakwok** [comment]
Seth and I discussed this a bit today, probably we'll go for a FM property to flag the FM to be `cross-partition` (since this is what really drive the need to have it configured last). This `IsCrossPartitionFM` flag should be unique per configuration, since we should have the freedom to put all the crossPartition crates into the same partition.

**Comment by kakwok** [comment]
After talking to Seth, we should probably do a check to make sure there is only 1 crossPartitionFM set to true. Will improve in the next PR.

**Comment by kakwok** [comment]
We should probably deprecate the `crossPartitionFM` feature as it is replaced by `configPriority`.
We simply have to assign the lowest configPriority to the crossPartitionFM to achieve the purpose.
