### ISSUE TITLE
Revise stopping sequence

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#280]
In this hcos issue[1] and during localDAQ development, we have difficulty to stop gracefully in the middle of a local run, so a re-work of stopping sequence to harmonize normal stopping(Completed taking all triggers) and stopping from user input.

What we do now: 
- LV1 stops all LV2 FM
- LV2 issues disable to TA and supervisor (not ordered by a TaskSequence)
- TA watchThreads polls the state of TA and issue disable to EvmTrig FM during a normal stopping.

New proposal:
- TA watchThreads polls the state of TA and either 
  1) signal LV1 to execute stopping action via a parameter which LV1 polls or 
  2) try to get LV1 FM to execute stopping action directly .
- LV1 schedule EvmTrig FM to stop first, then all other FMs in parallel
- LV2 FM schedule to stop TA first, wait until TA changes to ready(in normal stopping, this should be a no-op), then stop the supervisor

[1]https://gitlab.cern.ch/cmshcos/hcal/issues/25

**Comment by sethcooper** [comment]
For my clarity:

Current situation:
1. Run to completion
    - EvmTrigFM stopped by TA watchthread when TA is done with the run
    - Notification of this stopping triggers a computeState() which then fires the stop event to the L1 FM
    - Then the L1 stoppingAction is performed
2. Stop in the middle of the run
    - The L1 stoppingAction is performed.
    - The stop of the TA, however, does not end the run immediately but only when the current cycle of trigger credits has completed.

**Comment by kakwok** [comment]
I think this is correct.

**Comment by kakwok** [comment]
#328 
should harmonize the stopping sequence now, with a slightly different approach than original plan. Here is the stopping sequence: 
Auto stop:
- TA stops itself after taking all events
- TAwatchThread found TA was stopped and then stops the EvmTrig FM
- EvmTrig FM changes state to stopping ( thus notifies LV1 FM), disable TA again(ignored by TA) then disable supervisor
- LV1 FM execute stoppingAction
- LV1 stops the rest of the FMs (except EvmTrig FM)
- Rest of the FMs disable the supervisors.

Click stop:
- LV1 FM execute stoppingAction
- LV1 schedule to stop EvmTrig FM, then the rest of the LV2 FMs
- EvmTrig FM disables TA, wait for last event batch, then disable supervisor
- EvmTrig FM goes to configured
- The rest of LV2 FM disables their supervisors
