### ISSUE TITLE
goToError for missing instance number in maskapps names 

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#281]
We should validate the runkeys before parsing it. Details of implementation could be discussed.

**Comment by CiaranGodfrey** [comment]
[https://github.com/HCALRunControl/levelOneHCALFM/compare/integration...CiaranGodfrey:maskappsInstanceNumberCheck?diff=unified&expand=1&name=maskappsInstanceNumberCheck](url)

I added a function to validate the runkey when selected. If an instance number is missing the state will change to error and the program will stop running. I also added a section during parsing by the xml handler to throw an exception if the instance number is missing.

**Comment by CiaranGodfrey** [comment]
addresed in:

[https://github.com/HCALRunControl/levelOneHCALFM/pull/294](url)

maskedapps are validated on initialize and during runkey parsing

**Comment by kakwok** [comment]
Merged in #294
