### ISSUE TITLE
Allow partition-specific setting to be applied from FM

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#285]
Currently, we apply uniform snippets settings in Mastersnippets to all LV2 FMs. However, we sometimes may want to apply partition-specific settings, for example, to configure HO ici listening to TCDS resync Bgo.

We should design a syntax for mastersnippets for this purpose.

**Comment by kakwok** [comment]
Proposal:
Both LV1 and LV2 reads mastersnippets and set their parameters from there.
Mastersnippet should have two allowed syntax:
`A)<FMParameter>Value</FMParameter>`
`B)<FMParameter partition="partition_name">Value</FMParameter>`
TCDS snippets, with `xi:include` syntax, will be expand and concatenated before FM start setting the parameter to specified value.

If same parameter is specified with typeA and typeB, type B should have priority
If there is `partition` attribute in the tag, but the value do not match the FM's partition, the `Value` will be ignored.

**Comment by jhakala** [comment]
Should this be closed? It seems #363 does this, right?

**Comment by jhakala** [comment]
Closing this since (I'm pretty sure) it's done in #363.
