### ISSUE TITLE
Improvements for RunInfoDiffer

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#304]
1) Publish un-parsed mastersnippet 
FM should publish the un-parsed mastersnippet to make the diff from RunInfoDiffer more readable
2) Skip publishing to runinfo for `EMPTY_FMs` in the HCAL-fishy thread

**Comment by jhakala** [comment]
Moved this issue to https://github.com/HCALRunControl/RunInfoDiffer/issues/2
