### ISSUE TITLE
Un-hardcode HaltTCDS on destroy 

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#325]
When this hcos issue has been addressed https://gitlab.cern.ch/cmshcos/hcal/issues/81,
- Get the TCDS URLs from supervisor 
- Construct the TCDS containers from supervisors during initXDAQ
- if the containers are not empty, LV2s should send a halt to respective URLs on destroy.
- Should leave a warning message in case of failure.

**Comment by jhakala** [comment]
Should this issue be closed?
I'm a bit confused about the current TCDS handling. Just for my clarification: does the FM still use the method for sending commands to hardcoded URLs in order to free the TCDS hardware leases? If so, does that feature really buy us much any more?

**Comment by sethcooper** [comment]
If someone destroys and configures within 10 seconds, that feature prevents an error due to the lease not being released yet.  So yes, it does help, especially with sets of local runs taken in quick succession (such as during an interfill period).

**Comment by kakwok** [comment]
And yes, TCDS urls are still hardcoded in FM until hcos issue 81 is implemented

**Comment by jhakala** [comment]
> If someone destroys and configures within 10 seconds, that feature prevents an error due to the lease not being released yet

Is that the case anytime one destroys, or only if one destroys from the “Configured”/“Running”/“Error” states (plus the intermediate transitional states between those)?

**Comment by kakwok** [comment]
Supervisor cannot(like it crashed), and sometimes should not(like when we are configured) release the lease in all possible cases. It does not matter to me where the "from" state is, because FM have to give up the session when we destroy and sending an extra halt to TCDS is not a crime if supervisor already release the lease in some cases.
