### ISSUE TITLE
Include more than just supervisor error in large GUI error message

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#33]
Currently the error message that pops up in big red letters in the GUI is purely based on error messages the FM receives from the supervisor -- it is not indicative of other important errors which should be shown there -- e.g. the StateTransitionMessage sometimes contains important errors.

**Comment by sethcooper** [comment]
As far as xdaq issues go, adding the state transition message would also help fix some the messages in the logs with no supervisor error message:
2016-06-02 10:44:44 and 862 ms : cms.hcalpro.rcms.fm.app.level1.HCALEventHandler
    ERROR [HCAL LVL1 HCAL_LEVEL_1] Level 2 FM with name HCAL_HBHEc has received an xdaq error from the hcalSupervisor: 
That comes from pollLVL2FMhealth() in HCALEventHandler.

I suppose it makes sense to set the GUI error message in the goToError function.
How does one do that? Is it simply by setting a parameter?
We could also do a force refresh at that time in lieu of having an auto-update.

**Comment by jhakala** [comment]
The big red GUI error message is the SUPERVISOR_ERROR.

I'd prefer not doing force-refreshes since that's lazy compared with really doing parameter notifications and I don't want that to be a go-to instead of doing it correctly.

**Comment by sethcooper** [comment]
I'm all for doing it correctly so long as it doesn't take months to actually do it correctly.

**Comment by sethcooper** [comment]
In 382179bbe6370848d2e13d9006ad10393fca287c
ready to be tested

**Comment by jhakala** [comment]
done by Seth (awaiting confirmation in the logs/gui)
