### ISSUE TITLE
Accept more format on maskedapp input string

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#345]
- consider accept inputs like `maskedapps="crate:24,20,35…|Executive_1"`
 - wildcard masking like `ngRBXManager_*`

**Comment by jhakala** [comment]
It looks to me that #344 requests the crate number functionality. Having spoken with Martin about it, I don't think the wildcard functionality is something we want to do, so I am marking this as a duplicate and closing it.
