### ISSUE TITLE
Configuration progress and gui progress bar

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#36]
We should add functionality to the level2 to receive configuration progress reports from xdaq and store them as a function manager parameter. The level1 should do some calculation of the different level2s' configuration progress to make an overall configuration progress. Then it should be displayed in the gui for local runs. It could also be sent to the level0 instead of the hcalFishy.

**Comment by sethcooper** [comment]
Just to note that this parameter already exists in supervisor infospace as "overallProgress" (which will report the fraction which is shown as a percentage on the supervisor hyperdaq page).

**Comment by jhakala** [comment]
I think this is a duplicate for the fishy swimming across the action message. The fishy is more useful since it will appear in global as well as in local.
