### ISSUE TITLE
Add crate number to level2 FM error message

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#361]
Moved from [cmshcos/hcal#102](https://gitlab.cern.ch/cmshcos/hcal/issues/102).

When applications corresponding to a particular crate or board in a crate go to error or crash, it would be nice if the level2 FM added the crate number to the error message by looking through the RS group and finding the offending app's associated crate number by accessing it from the application property of the corresponding hcalCrate app's application properties.

**Comment by kakwok** [comment]
As an example, the improved error message could look like this: 
```[LV1 FM] Error received: [HCAL_HBHEb] Application(s) in error : [hcal::DTCManager::crateXX] 
error message from hcalSupervisor: Unable to create class: Bad AMC13 instance, AMC13::initAMC13() - Error reading firmware version from T1 or T2 ```

**Comment by jhakala** [comment]
I see that this has been implemented in an alternative way, which I am not too fond of:
https://github.com/HCALRunControl/levelOneHCALFM/pull/394/files#diff-dc1b08236f84b79be1b18d47967b6599R92
Please see my comment on the diff a little below where that links.

**Comment by jhakala** [comment]
Done using the new qgMapper in #404
