### ISSUE TITLE
Restore or improve SUPERVISOR_ERROR in errMsgFormat branch

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#389]
See #374. In particular, see the screenshot of the new table for displaying the Supervisor's vectors of error messages from its apps, as well as the modified SUPERVISOR_ERROR above it.

The SUPERVISOR_ERROR that we see in that branch is missing the content that it used to have. We should either restore that content through some newer trickery or simply revert whatever changes were made to it so that it has the same content as it had before. The reason it should contain all the old content is because that error message gets propagated to the L0 and also gets written to the logs; in those places we want to preserve the full content.

Once the old content of the SUPERVISOR_ERROR is restored, we can then figure out if we e.g. want to get rid of showing it in the GUI.

**Comment by kakwok** [comment]
I think the easiest thing to do would be for GUI to display the error message table when the content is not null/empty. In case supervisor crashed/ failed to initialise, we won't have the error message as table, then the GUI can display the SUPERVISOR_ERROR as a string.
Can this be done?

**Comment by jhakala** [comment]
Yes, that could be done.

Maybe there is another possible way to do it that might be better but not quite as easy, let me know what you think about this proposal: How about we also stick the FM-related errors (like, e.g. in the case where the supervisor crashed or failed to start; or if an FM has problems, e.g. in the case a level2 gets an invalid parameter setting) into the parameter that populates the new table. (We could also consider changing the name `XDAQ_ERR_MSG` of the parameter in this case). If we did that, then it would be simple to only show the new error table in the local gui. I think it would be useful to organize the FM-level errors in this way too; e.g. so that one could easily see if there was only one or if there were multiple partitions that had errors. 

For the global error message, I think it would be best to return the `SUPERVISOR_ERROR` back to how it was so that the error message the level0 gets stays the same as what is currently deployed.

**Comment by kakwok** [comment]
OK. I think the fix is simpler than i thought: LV1 ignores the LV2's long SUPERVISOR_ERROR message string when supervisor reported a more detailed error to LV2. Here are the two different test case:
![image](https://user-images.githubusercontent.com/12798013/37873692-2ee9dc38-3022-11e8-8125-32bf05fbdbfe.png)

![image](https://user-images.githubusercontent.com/12798013/37873689-17088c90-3022-11e8-9f84-d66c9f498b78.png)

**Comment by kakwok** [comment]
done in 73dfcafe11c31cf347657c11ed9ec91bd336b24a and 3efa29f
