### ISSUE TITLE
"Globalize" the FM by using level0 run key with local run key functionality

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#40]
Right now the FM depends on user input through the HCALFM gui to get things like its mastersnippet name and list of masked apps. We should have some server-side code handle this without HCALFM gui user input, so that we can run in global. Then we can use the level0's RUN_KEY parameter (which is currently a ZS snippet switch) for things the local run key can do.

**Comment by jhakala** [comment]
This is mostly done, pending investigation on configuration failure after a green recycle/warm init.

**Comment by jhakala** [comment]
But we should still think about using the level0 RUN_KEY parameter....

**Comment by kakwok** [comment]
I propose to demote this issue to medium piority, as the feature is not needed by RC and there seems not a urgent need from our side too.

**Comment by jhakala** [comment]
I think this issue has no more relevance now -- the globalization is done, and the l0 RUN_KEY is basically useless since user error potential outweighs potential benefits from this, while FM masking via userXML gives the HCAL DAQ on call a quick way to utilize the masking features that fills any remaining gaps.
