### ISSUE TITLE
Fix TTCci handling on stopping in configurations with a DummyTA

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#41]
Currently runs that use the TTCciControl and a DummyTriggerAdapter don't stop automatically. Needs diagnosis/fix

**Comment by sethcooper** [comment]
Do we know which FMs don't stop?  Does the level-1 go into the Stopping state?

**Comment by sethcooper** [comment]
Fixed in 904.
Needs testing in P5.

**Comment by sethcooper** [comment]
John tested this at P5 on April 19, 2016, and it worked.
bam
