### ISSUE TITLE
Make maskedapps and maskedcrates optional in runkey

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#410]
`maskedapps` and `maskedcrates` attributes are optional in the xsd, but we rely on having `maskedapps=''` and `maskedcrates=''` to provide initial values for the GUI.

**Comment by jhakala** [comment]
Done in #411.

**Comment by jhakala** [comment]
Tested at 904, this works AOK (and I was able to reproduce the prior error, it is now gone).
