### ISSUE TITLE
Investigate/fix green recycle/warm-init issue

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#48]
It seems that after a Stop->Green Recycle, the FM hangs in configuring state due to a supervisor failing to go from warm-init state into configured state. This needs diagnostics and possibly a fix in the HCALFM code.

Note that green recycle is equivalent to "halt, reconfigure", so this should be reproducible in a teststand local run.

**Comment by jhakala** [comment]
The issue seems to come from this line in the hcalSupervisor:
http://cmshcalweb01.cern.ch/lxr/source/HCOS/trunk/hcalSupervisor/src/common/hcalSupervisor.cc#1477

It's not clear why getCfgDatabase should fail on "Initializing" but not "Warm-Initializing," so this needs futher attention.

**Comment by sethcooper** [comment]
Fix in supervisor to releaseCfgDatabase when using the workCfgScript() function to parse INCLUDEs in the CfgDoc.
Tested at 904.
