### ISSUE TITLE
Allow FM masking via userXML (in global runs)

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#50]
Right now adding the name of an FM to the maskedapps attribute in the userxml for the local run keys will fail to mask that FM.

**Comment by kakwok** [comment]
This works in local run since commit 3e81fa9. I'm working to make the feature works in miniDAQ.

**Comment by kakwok** [comment]
This works now with global/miniDAQ after 396e7ac

**Comment by jhakala** [comment]
This failed when I tried to mask the TCDSLPM FM via the userXML. However, it worked when I did it using the GUI checkboxes. Perhaps this is a special case, but this needs to be fixed.

**Comment by kakwok** [comment]
I checked the RSManager history that the maskedFM attribute has not been set for that runkey. 
We should test it next time when this is needed.
I put two example usage here:
For masking one FM:
<RunConfig name='pedestal_noHO' snippet='Master/uTCA+VME_pedestal.xml' maskedFM='HCAL_HO'/>'
For masking more than 1 FM: separate with ";"
<RunConfig name='pedestal_noHOnoHF' snippet='Master/uTCA+VME_pedestal.xml'  maskedFM='HCAL_HO;HCAL_HF'/>

**Comment by kakwok** [comment]
Tested again. it works. Documentation is in elog, FM twiki and this issue page.
An example runkey is also left in the local run userXML: pedestal_noHOnoHF.
