### ISSUE TITLE
Add functionality for including a "common" mastersnippet

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#51]
All of our mastersnippets include some of the same information that is common to all mastersnippets. We should create some common mastersnippet and implement including it by default in the HCALFM. Then only the things specific to a particular mastersnippet will need to be in the various runs' mastersnippets.

**Comment by kakwok** [comment]
Implemented in HCALFM_74c8966.jar (code not pushed yet)
Current implementation:
1) Master/common.xml as a common MS.
2) In getCfgScript(), the LV1 FM will get the includes from common first(if any), then stick it in before the content of MS from run key.
3) Add a line in userXML to use.

The parsing part went well, correct MS is assembled from two files. However, the run stalled (0 events pending) when we have double-include from common MS and run key MS.

**Comment by sethcooper** [comment]
Runs can stall for many reasons.
In principle hcos should have no problem with double includes. But it does make the resulting script a little messy.
We could add a check in the FM to make sure there are no double INCLUDES.

**Comment by kakwok** [comment]
Indeed the condition was unclear during the test. Could be simply due to
not masking HO at the time.
I'll retest the double includes in H2 / 904. I'll also look into FM checks.

**Comment by jhakala** [comment]
This may be a bit more delicate than just needing a check for double includes. If we start validating basic things about the CfgDoc then we're starting down the road to doing config validation in the HCALFM, but it's not clear that this should be the FM's job. If we check for double includes, then why not check for contradicting includes, missing includes, or even the content in the snippets themselves?

So we should make a decision on where to implement config validation checks considering that there are already tools for this under development.

**Comment by jhakala** [comment]
I've bumped this up to high because it would be extremely useful to have this feature to enable the running degraded states in all run configurations. It is impractical to have to edit all our snippets to make this change.

**Comment by kakwok** [comment]
The common MS feature as implemented now only supports for <CfgScript> tag, so it only stick in the common MS content when it tries to get CfgScript from MS. 
An easy way around is to tell the get alarmerURL function to look for the tag in the common MS instead of chosen MS.

**Comment by sethcooper** [comment]
What is the status on this?
It looks like we have a good use case here, that of having separate common MS for local and global run configurations so that we can specify special settings for local runs in the CfgScript.
This is currently done in all local run MS for the trigger adapter, for example, while it would be much nicer to have it once in the common MS.

**Comment by kakwok** [comment]
Tested on H2 again. Double-include is OK. The include from common MS will come first, so it will be overwritten by the MS from the local run key.
Example Usage:
1) In userXML:
<Common name='MasterSnippet' snippet='H2/CommonMS.cfg' />
ps. We can add other things in "Common" tag if we want.

2) The CommonMS should be like the other MS:
<mastersnippet>
<CfgScript>
  include(/H2/Global.cfg:pro)
</CfgScript>
</mastersnippet>

**Comment by kakwok** [comment]
Read the commonMS tag from MS instead of from userXML

**Comment by kakwok** [comment]
Fixed. 
Now we need a tag like this in the main mastersnippet:

`<CommonMS>H2/CommonMS.cfg</CommonMS>`

NO spaces in between tag! As it will be used as the file path.

**Comment by jhakala** [comment]
merged

**Comment by kakwok** [comment]
For the record, the syntax should be:
<CommonMasterSnippet file="H2/CommonMS.cfg" />

**Comment by kakwok** [comment]
Rework:
1) Write a function to parse a mastersnippet file
2) Fill the necessary info in parameters
    When filling the CfgScript, concat the string instead of overwriting the parameter
    Otherwise overwrites.

Simply calls the function twice during LV1 ConfigureAction
First on common MS then main MS.

**Comment by kakwok** [comment]
#126 done
