### ISSUE TITLE
Port HCALFM / RCMS into an eclipse project

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#57]
It would be nice if we could have RCMS and the HCALFM as an eclipse project so that, for example, it can automatically index available methods for RCMS objects as well as locating appropriate imports.

**Comment by frozen-sapiens** [comment]
It's done on H2, though RCMS had to be added as external project and then added as dependency, I think wiki will be the best way to describe the process

**Comment by jhakala** [comment]
Can the progress on this be documented?

It would be ideal if eclipse would recognize the RCMS framework methods -- so let's not close this issue until we can achieve that -- but incremental progress on this would be appreciated.

Note that the central RCMS team (including Hannes and Philipp who are quick to give useful feedback) already have RCMS as an eclipse project, so drawing on their tools might expedite this.

**Comment by jhakala** [comment]
Done with PR #182.
Instructions are on the twiki: https://twiki.cern.ch/twiki/bin/view/CMS/HCALFunctionManager#Developing_the_HCALFM_in_Eclipse
