### ISSUE TITLE
Remove unused xml from mastersnippets

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#58]
There is a lot of stuff in the mastersnippets now which is unused. We should determine what is not being used and remove it.

**Comment by sethcooper** [comment]
@kakwok you were starting on this, right?

**Comment by kakwok** [comment]
Yes.
2016年4月20日 08:08 於 "sethcooper" <notifications@github.com> 寫道：

**Comment by kakwok** [comment]
Done
