### ISSUE TITLE
Make the hcalFishy swim across the action message during configuring in global

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#64]
The hcalFishy swims randomly around the ACTION_MESSAGE during Configuring. It would be more useful if he swam across from left to right to indicate configuration progress. Note that this is different from the configuration progress bar because this needs to be done purely on the server side in HCALEventHandler.MoveTheLittleFishy

**Comment by kakwok** [comment]
The localcompletion needs to find a new place to live since we are removing waitForSupervisor() in async world.   #160  
https://github.com/HCALRunControl/levelOneHCALFM/commit/83d5ae83c4abcef4806e7b02d7144f943338e05f#diff-58e1557a763b39a55b18c1cfbef7e57aL1892

**Comment by jhakala** [comment]
I've started working on this -- I'd rather abandon the old localcompletion and COMPLETION stuff and start from something simpler. It seems there is an issue with the Lvl1MonitorThread

**Comment by jhakala** [comment]
I made a commit to the "progress" branch that should give us a realtime-updating parameter "PROGRESS" in the GUI (in the Global Parameters table) that gives a numerical value for the configuration progress, and prints out some info into the logs about the numbers its using internally to calculate the progress. 

I'd appreciate if this could be tested at P5 to make sure the parameter in the GUI is working as desired (it should go from 0 to 1 during configure). If this works we can pursue making a useful fishy message.

**Comment by jhakala** [comment]
I've changed the title of the issue to "Configuration Progress Bar" because using the fishy swimming as a progress bar probably won't give us the desired granularity, so it's better we:
- have a normal progress bar 
  - done in #198 
- just print a numerical value to the ACTION message
