### ISSUE TITLE
Disable userXML-masked FM check-box in GUI

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#74]
Now we allow userXML to mask FM via the syntax:
`<RunConfig name='localrunkey' snippet='Master/myMS' maskedFM='FMname' />`
So, in the gui, we should read the list of masked FM, fill that into the Masked Resource box and disable the corresponding check-boxes in the "MaskedFM" menu.

**Comment by jhakala** [comment]
This probably should wait until after the grandmaster #110.

**Comment by jhakala** [comment]
Superseded by #202.
