### ISSUE TITLE
Clean up async supervisor communication

### ISSUE THREAD

**Issue by kakwok** [HCALRunControl/levelOneHCALFM#84]
Currently there're 2 key switches 
1) AsyncSOAP (FM parameter)
2) HCALSupervsiorAsyncEnable (defined in event Handler, read from userXML)

For asyncSOAP :
During initAction, it reads the value from FM properties and stays there.
**Therefore, at P5, this is false at all times.**

During ConfigureAction, this affect two places:
sendRunTypeConfiguration, it's used to determine this HCALSuperVisorIsOK:
      if (functionManager.asyncSOAP) { HCALSuperVisorIsOK = false; } 
and wait for supervisor:
      if ( (!functionManager.asyncSOAP) && (!functionManager.ErrorState) ) 
          {    waitforHCALsupervisor();     }

For HCALSupervsiorAsyncEnable:
During initAction, reads from userXML, in P5, it's **false**.
During startAction, the LV2s will send AsyncSTART/ START based on that:
    if (HCALSupervisorAsyncEnable) {
            functionManager.containerhcalSupervisor.execute(HCALInputs.HCALASYNCSTART);          }
          else {
            functionManager.containerhcalSupervisor.execute(HCALInputs.HCALSTART);          }
**AND** 
this also determines if the LV2 will have another state calculation:
In StartAction of LV2 EventHandler:
      if (!HCALSupervisorAsyncEnable) {
        // leave intermediate state only when not talking to asynchronous applications
        if ( (!functionManager.asyncSOAP) && (!functionManager.ErrorState) ) {
          logger.info("[HCAL LVL2 " + functionManager.FMname + "] fireEvent: " + HCALInputs.SETSTART);
          functionManager.fireEvent( HCALInputs.SETSTART );
        }
      }

**Comment by sethcooper** [comment]
Firing any event (including SETSTART) does not have any effect on state calculations.

In general, a state notification at any time should trigger a state calculation (this is not entirely true, as the calculation is not done if the notification is from Configuring to Configuring, for example, and in a few other cases).

**Comment by jhakala** [comment]
bumping this up to high, since we want async ASAP

**Comment by kakwok** [comment]
Plan from the discussion on 12July:
-Async mode should be default in FM
-Implement all Async commands to the supervisors.

**Comment by sethcooper** [comment]
I would add: remove the sync stuff and special switches for async

**Comment by sethcooper** [comment]
Mostly addressed by #160

**Comment by sethcooper** [comment]
Actually I think this is completely addressed by #160 (aside from some clean up of code that's no longer used).
