### ISSUE TITLE
Make HCAL and HF global configurations look at corresponding alarmer statuses

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#86]
The HCALFM code will need to be changed so that the HCAL/HF global/minidaq configurations look not at the Global status from the new alarmer, but rather at the HB/HE/HO status and HF status respectively. There is also the possibility that we would like to observe the "dev" status or the other status, too, or even a combination of two or more statuses simultaneously. So we should design:
1) A way to easily configure the FM to look at one or more statuses -- probably a userXML element that specifies a list of the statuses to check
2) Logic in the FM to combine multiple statuses into the FM RunningDegraded calculation.

**Comment by kakwok** [comment]
Current implementation of the RunningDegraded is the following:
1) LV1 reads "alarmerURL" from mastersnippet
<AlarmerURL>http://hcalmon.cms:9955</AlarmerURL>
and stores it in a FM parameter.

2) Starts the alarmer watchthread on configureAction with the URL
3) Get the name of parameter via XDAQParameter:
            pam.select(new String[] {"GlobalStatus"});
            pam.get();
            String status = pam.getValue("GlobalStatus");

Proposal:
1) LV1 reads "AlarmerStatus" from mastersnippet:
<AlarmerStatus partition="HF" expectedStatus="OK" devStatus="NA"></AlarmerStatus>
write a getAlarmerStatus() to store them in FM parameters.

2) Start the alarmer watchthread with the parameters:
 -Need to map from "HF" to the XDAQParameter in alarmer code.
 
  e.g.If functionmanager.AlarmerPartition equals ("HF")
  then
  in LV1 :        AlarmerWatchThread thread4 = new AlarmerWatchThread("HFStatus");       
  then           pam.getValue(StringFromAlarmerConstructer);

 -ExpectedStatus and devStatus can be later used to do fancy logic

Ted's request in elog:
http://cmsonline.cern.ch/cms-elog/922720

**Comment by kakwok** [comment]
For HF the string should be "HFStatus"
For HBHEHO the string should be "GlobalStatus"
For HBHEHO the string should be "DEVStatus"

**Comment by kakwok** [comment]
Implemented In branch AlarmerUpdate.
Instead of passing argument to start the watchthread, I updated the watchthread to read the coorect XDAQ parameter in alarmer according to the mastersnippet tag.

**Comment by kakwok** [comment]
tested in miniDAQ and worked.

**Comment by jhakala** [comment]
Martin did this -- I think it works on our side now.
