### ISSUE TITLE
Investigate missing run numbers at 904

### ISSUE THREAD

**Issue by jhakala** [HCALRunControl/levelOneHCALFM#88]
In recent 904 runs, we always have run number 0. However, the run number should be assigned automatically just like P5 after establishing a connection with the RunInfo database. Perhaps we are missing some sort of necessary configuration such that the 904 FM gets the correct RunInfo connection.

**Comment by sethcooper** [comment]
<UseOfficialRunNumbers>true</UseOfficialRunNumbers>?
it does get what looks like a valid sessionID...

**Comment by jhakala** [comment]
Seth remembers correctly; I added this to VME_uTCA and it works.
