### ISSUE TITLE
Destroy supervisors first on destroy

### ISSUE THREAD

**Issue by sethcooper** [HCALRunControl/levelOneHCALFM#92]
We get occasional issues during destroy, where applications a supervisor talks to have already been destroyed, and the supervisor tries to talk to them, sending the supervisor into failed and printing a bunch of error messages.  Though this isn't hurting things too badly, we should destroy the supervisors first (either directly or by find its parent exec and destroying that) so that we eliminate this. I guess that this can just be added to the destroyAction(), as we seem to be destroying all execs in no particular order there. We should better document how the destroy works, as the destroyAction() is in HcalFunctionManager and destroy() is in HcalEventHandler, while normally I'd expect the *Action functions all to be in the eventhandler. Could be a framework-imposed constraint.

**Comment by sethcooper** [comment]
in 35e30fefed6169ea902959c5805fd8584644713c
ready for testing at p5

**Comment by jhakala** [comment]
merged
